apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-udagram-frontend
  name: app-udagram-frontend-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/app-udagram-frontend-svc
spec:
  type: LoadBalancer
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  selector:
    app: app-udagram-frontend