apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-udagram-gateway
  name: app-udagram-gateway-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/app-udagram-gateway-svc
spec:
  type: LoadBalancer
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  selector:
    app: app-udagram-gateway