apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-udagram-users
  name: app-udagram-users-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/app-udagram-users-svc
spec:
  ports:
  - protocol: "TCP"
    port: 8882
    targetPort: 8882
  selector:
    app: app-udagram-users